name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  golangci:
    name: lint

    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.18.x ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
